// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School.API.Persistence;

#nullable disable

namespace School.API.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("School.API.Data.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("264c8389-29ba-4193-b0e5-eb8ffb39c074"),
                            CourseId = new Guid("395c8760-c586-469e-b4fa-09a791b9aa34"),
                            CreatedBy = "Admin",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 10, 24, 8, 21, 38, 932, DateTimeKind.Unspecified).AddTicks(7232), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Web API in .NET 7 for Beginners",
                            Duration = 3,
                            ModifiedBy = "Admin",
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 10, 24, 8, 21, 38, 932, DateTimeKind.Unspecified).AddTicks(7235), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Web API in .NET 7",
                            PictureUrl = "https://stforeshop.blob.core.windows.net/coursesimages/WebAPIin_NET7.PNG"
                        },
                        new
                        {
                            Id = new Guid("014765b7-503c-4aae-96e4-495f752d2930"),
                            CourseId = new Guid("5b675f12-3e38-4ec7-b230-d791109cf4b5"),
                            CreatedBy = "Admin",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 10, 24, 8, 21, 38, 932, DateTimeKind.Unspecified).AddTicks(7240), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Minimal API in .NET 7 for Beginners",
                            Duration = 3,
                            ModifiedBy = "Admin",
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 10, 24, 8, 21, 38, 932, DateTimeKind.Unspecified).AddTicks(7241), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Minimal API in .NET 7",
                            PictureUrl = "https://stforeshop.blob.core.windows.net/coursesimages/MinimalAPIin_NET7.PNG"
                        },
                        new
                        {
                            Id = new Guid("17704f58-1c49-403e-8d1f-59cb6721d991"),
                            CourseId = new Guid("39763c01-3295-445d-bd89-7f26306416d2"),
                            CreatedBy = "Admin",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 10, 24, 8, 21, 38, 932, DateTimeKind.Unspecified).AddTicks(7262), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Blazor WASM in .NET 7 for Beginners",
                            Duration = 5,
                            ModifiedBy = "Admin",
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 10, 24, 8, 21, 38, 932, DateTimeKind.Unspecified).AddTicks(7262), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Blazor WASM in .NET 7",
                            PictureUrl = "https://stforeshop.blob.core.windows.net/coursesimages/BlazorWASMin_NET7.PNG"
                        },
                        new
                        {
                            Id = new Guid("ac865643-51a7-4943-ba69-84fb1eb6cacf"),
                            CourseId = new Guid("d5ed2000-5937-4717-a32f-6d755ddfb61b"),
                            CreatedBy = "Admin",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 10, 24, 8, 21, 38, 932, DateTimeKind.Unspecified).AddTicks(7264), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "gRPC in .NET 7 for Beginners",
                            Duration = 5,
                            ModifiedBy = "Admin",
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 10, 24, 8, 21, 38, 932, DateTimeKind.Unspecified).AddTicks(7265), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "gRPC in .NET 7",
                            PictureUrl = "https://stforeshop.blob.core.windows.net/coursesimages/gRPCin_NET7.PNG"
                        },
                        new
                        {
                            Id = new Guid("1f6ff906-602c-43f1-8785-f13bf104c562"),
                            CourseId = new Guid("4ac8f6a2-306e-4493-90e5-17c75ac8aa71"),
                            CreatedBy = "Admin",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 10, 24, 8, 21, 38, 932, DateTimeKind.Unspecified).AddTicks(7266), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "App Services in Azure for Beginners",
                            Duration = 9,
                            ModifiedBy = "Admin",
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 10, 24, 8, 21, 38, 932, DateTimeKind.Unspecified).AddTicks(7267), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "App Services in Azure",
                            PictureUrl = "https://stforeshop.blob.core.windows.net/coursesimages/AppServicesinAzure.PNG"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
